config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests, only: [:new, :create]
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base
  COLORS = %w(black white orange grey).freeze

  validates :birth_date, :color, :name, :sex, :description,
            presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w(M F) }

  has_many :cat_rental_requests, dependent: :destroy

  def self.colors
    COLORS
  end

  def age
    age_in_days = (Time.now.to_date - birth_date).to_i
    age_in_days / 365
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def does_not_overlap_approved_request
    # unless overlapping_approved_requests.empty?
    #   errors[:base] << "Cannot overlap with approved rental request"
    # end
    if overlapping_approved_requests.exists?
      errors[:base] << "Cannot overlap with approved rental request"
    end    
  end

  private

  def overlapping_requests
    CatRentalRequest
      .where("((?) > start_date AND (?) < end_date OR (?) > start_date AND (?) < end_date) AND cat_id = (?)",
            self.start_date, self.start_date, self.end_date, self.end_date, self.cat_id
            )
  end

  def overlapping_approved_requests
    # overlapping_requests.select do |request|
    #   request.status == "APPROVED"
    # end
    overlapping_requests.where(status: "APPROVED")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    render :new
  end

  def create
    @rental = CatRentalRequest.new(cat_rental_params)
    if @rental.save
      redirect_to cat_url(@rental.cat_id)
    else
      render :new
    end
  end

  private

  def cat_rental_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat.id)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat.id)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex,
                                :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Rental Request for Cat</h1>

<section>

  <form action="<%= cat_rental_requests_url %>" method="post">

    <label for="cat">Choose a cat to rent: </label>
    <select id="cat" name="rental[cat_id]">
      <option selected disabled>Select a Cat</option>
      <% @cats.each do |cat| %>
        <option value="<%= cat.id %>"><%= cat.name %></option>
      <% end %>
    </select>

    <br>

    <label for="start_date">Start Date</label>
    <input type="date" id ="start_date" name="rental[start_date]">

    <br>

    <label for="end_date">End Date</label>
    <input type="date" id ="end_date" name="rental[end_date]">

    <br>

    <input type="submit" value="Request rental">

  </form>

</section>

app/views/cats/_cat.html.erb
<li>
  <%= cat.name %>, <%= cat.age %> year(s) old.
  <a href="<%= cat_url(cat.id) %>">Details</a>
</li>

app/views/cats/_form.html.erb
<% action_url = (action == :new) ? cats_url : cat_url(cat.id) %>
<% submission_type = (action == :new) ? "Add cat!" : "Update #{cat.name}!" %>

<section>
  <form action="<%= action_url %>" method="post">
    <% if action == :edit %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="name">Cat Name</label>
    <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">

    <br>
    <br>

    <label for="birth_date">Cat Birthday</label>
    <input type="date" id ="birth_date" name="cat[birth_date]" value="<%= cat.birth_date %>">

    <br>
    <br>

    <label for="color">Cat Color</label>
    <select id="color" name="cat[color]">
      <option disabled>Select Cat Color</option>
      <% Cat.colors.each do |color| %>
        <option value="<%= color %>"
          <%= cat.color == color ? "selected" : "" %>><%= color.capitalize %></option>
      <% end %>
    </select>

    <br>
    <br>

    <label for="sex">Sex</label>
    M<input type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
    F<input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>>

    <br>
    <br>

    <label for="description">Description
      <textarea
      id="description"
      name="cat[description]"
      cols="30"
      rows="10"><%= cat.description %></textarea>
    </label>

    <br>
    <br>

    <input type="submit" name="" value="<%= submission_type %>">
  </form>
</section>

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %>!</h1>
<%= render "form", cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>Cats</h1>

  <section>
    <ul>
      <% @cats.each do |cat| %>
          <%= render cat %>
      <% end %>
    </ul>
    <br>

    <%= link_to "Add new cat", new_cat_url %>
  </section>

app/views/cats/new.html.erb
<h1>Add a new cat!</h1>
<%= render "form", cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1><%= @cat.name %>'s Page</h1>

  <section>

    <h2>Bio</h2>

    <table>
      <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Sex</th>
        <th>Age</th>
        <th>Description</th>
      </tr>
      <tr>
        <td><%= @cat.name %></td>
        <td><%= @cat.color %></td>
        <td><%= @cat.sex %></td>
        <td><%= @cat.age %></td>
        <td><%= @cat.description %></td>
      </tr>
    </table>
  </section>

  <br>

  <section>

    <h2>Rental Reservations</h2>

    <table>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
      </tr>
      <% @cat.cat_rental_requests.order("start_date").each do |request| %>
        <tr>
          <td><%= request.start_date %></td>
          <td><%= request.end_date %></td>
        </tr>
      <% end %>
    </table>
  </section>

  <br>

  <%= link_to "Cats Home", cats_url %>
  <%= link_to "Edit #{@cat.name}", edit_cat_url(@cat.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatSite</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>